version: 0.0
os: linux
files:
  - source: /
    destination: /app
hooks:
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 600
      runas: root
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 60
      runas: root
