# Set up all your desired environment variables here. Figaro will take care of making sure they're visible to the
# splits-io.

production:
  splitsio_db_host:
  splitsio_db_name:
  splitsio_db_username:
  splitsio_db_port:
  splitsio_db_password:
  NEW_RELIC_LICENSE_KEY:

  # set up twitch stuff at twitch.tv/settings/connections
  TWITCH_CLIENT_ID:
  TWITCH_CLIENT_SECRET:

  ROLLBAR_ACCESS_TOKEN:

development:
  # sqlite should work just fine for a development database

  # for login in development, you'll want a separate client on twitch with a localhost redirect uri
  TWITCH_CLIENT_ID:
  TWITCH_CLIENT_SECRET:

splitsio_secret_key_base:

# hot is development mode hitting the production database. so db info below should be prod; everything else below, dev.
hot:
  splitsio_db_host:
  splitsio_db_name:
  splitsio_db_username:
  splitsio_db_port:
  splitsio_db_password:

  TWITCH_CLIENT_ID:
  TWITCH_CLIENT_SECRET:
