version: 0.2

env:
  variables:
    DOCKER_HOST: tcp://127.0.0.1:2375
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker-compose version
      - docker-compose build
      - docker-compose run -e RAILS_ENV=test web rails db:migrate
      - docker-compose run -e RAILS_ENV=test web rspec
      - docker save splits-io_web | gzip -c > web.tar.gz
      - docker save splits-io_worker | gzip -c > worker.tar.gz
      - zip dist.zip web.tar worker.tar
  post_build:
    commands:
      - echo Build completed! wixSanic
