development: &development
  adapter: redis
  url: "redis://redis:6379/1"

profiling:
  <<: *development

test:
  adapter: redis
  url: "redis://redis:6379/1"

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: cable
